#!/bin/bash

# Server Health Check Script
# Dit script helpt bij het debuggen van de productieserver

echo "========================================="
echo "Server Health Check voor 209.38.40.156"
echo "========================================="
echo ""

SERVER="209.38.40.156"

echo "1. Check of de server bereikbaar is:"
echo "-----------------------------------"
ping -c 3 $SERVER

echo ""
echo "2. Check of port 5000 open is:"
echo "-------------------------------"
nc -zv $SERVER 5000 2>&1

echo ""
echo "3. Check of port 80 (nginx) open is:"
echo "-------------------------------------"
nc -zv $SERVER 80 2>&1

echo ""
echo "4. Test health endpoint met curl:"
echo "----------------------------------"
curl -v http://$SERVER:5000/api/health 2>&1

echo ""
echo "5. Test nginx proxy (indien geconfigureerd):"
echo "--------------------------------------------"
curl -v http://$SERVER/api/health 2>&1

echo ""
echo "========================================="
echo "Commands om op de server uit te voeren:"
echo "========================================="
echo ""
echo "SSH naar de server:"
echo "ssh user@$SERVER"
echo ""
echo "Eenmaal ingelogd, voer deze commands uit:"
echo ""
echo "# 1. Check of PM2 draait:"
echo "pm2 status"
echo ""
echo "# 2. Check PM2 logs voor errors:"
echo "pm2 logs backend-server --lines 50"
echo ""
echo "# 3. Check of Node.js applicatie draait:"
echo "ps aux | grep node"
echo ""
echo "# 4. Check nginx status:"
echo "sudo systemctl status nginx"
echo ""
echo "# 5. Check nginx error logs:"
echo "sudo tail -f /var/log/nginx/error.log"
echo ""
echo "# 6. Check of .env file bestaat:"
echo "ls -la /var/www/learnai/server/.env"
echo ""
echo "# 7. Test database connectie:"
echo "mysql -h localhost -u root -p db -e 'SELECT 1'"
echo ""
echo "# 8. Check firewall regels:"
echo "sudo ufw status"
echo ""
echo "# 9. Check of port 5000 luistert:"
echo "sudo netstat -tulpn | grep :5000"
echo ""
echo "# 10. Restart de backend server:"
echo "pm2 restart backend-server"
echo ""
echo "========================================="
echo "Mogelijke problemen en oplossingen:"
echo "========================================="
echo ""
echo "1. Applicatie niet geïnstalleerd:"
echo "   - Volg deployment.md instructies"
echo ""
echo "2. PM2 draait niet:"
echo "   - pm2 start ecosystem.config.js"
echo ""
echo "3. Database connectie faalt:"
echo "   - Check .env file: DB_HOST=localhost"
echo "   - Check MySQL draait: sudo systemctl status mysql"
echo ""
echo "4. Firewall blokkeert port 5000:"
echo "   - sudo ufw allow 5000"
echo ""
echo "5. Nginx niet geconfigureerd:"
echo "   - Volg nginx setup in deployment.md"