#!/bin/bash

echo "====================================="
echo "DEBUG .env FILE LOADING ISSUE"
echo "====================================="
echo ""
echo "Voer deze commands uit op de server (209.38.40.156):"
echo ""
echo "# 1. Check de inhoud van de .env file:"
echo "cd /var/www/learnai/server"
echo "cat .env"
echo ""
echo "# 2. Check file permissions:"
echo "ls -la .env"
echo ""
echo "# 3. Check of er speciale characters in het bestand zijn:"
echo "file .env"
echo "hexdump -C .env | head -20"
echo ""
echo "# 4. Check of dotenv correct geïnstalleerd is:"
echo "ls -la node_modules/dotenv"
echo ""
echo "# 5. Maak een backup en hermaak het bestand:"
echo "cp .env .env.backup"
echo "rm .env"
echo ""
echo "# 6. Maak een nieuwe .env file (let op: geen quotes rond values!):"
echo 'cat > .env << "EOF"'
echo "PORT=5000"
echo "NODE_ENV=production"
echo "DB_HOST=localhost"
echo "DB_USER=root"
echo "DB_PASSWORD=BoomBoom10!Baby"
echo "DB_NAME=db"
echo "DB_PORT=3306"
echo "JWT_SECRET=your-production-jwt-secret-change-this-12345"
echo "JWT_EXPIRE=7d"
echo "SESSION_SECRET=your-production-session-secret-change-this-67890"
echo "FRONTEND_URL=http://209.38.40.156"
echo "BACKEND_URL=http://209.38.40.156:5000"
echo "EOF"
echo ""
echo "# 7. Set correcte permissions:"
echo "chmod 644 .env"
echo "chown www-data:www-data .env"
echo ""
echo "# 8. Test direct met Node.js:"
echo "node -e \"require('dotenv').config(); console.log(process.env.DB_PASSWORD);\""
echo ""
echo "# 9. Als dat werkt, restart PM2:"
echo "pm2 restart backend-server"
echo "pm2 logs backend-server --lines 30"
echo ""
echo "====================================="
echo "ALTERNATIEF: Test met hardcoded values"
echo "====================================="
echo ""
echo "# Test of MySQL uberhaupt werkt:"
echo "mysql -u root -pBoomBoom10!Baby -e 'SHOW DATABASES;'"
echo ""
echo "# Start de server direct zonder PM2 om errors te zien:"
echo "cd /var/www/learnai/server"
echo "DB_HOST=localhost DB_USER=root DB_PASSWORD='BoomBoom10!Baby' DB_NAME=db node src/server.js"
echo ""
echo "====================================="
echo "MOGELIJKE OORZAKEN:"
echo "====================================="
echo "1. .env file heeft Windows line endings (CRLF)"
echo "2. .env file heeft BOM characters"
echo "3. Verkeerde file permissions"
echo "4. PM2 cached oude environment variables"
echo "5. Syntax error in .env file"
echo ""
echo "PM2 CACHE CLEAREN:"
echo "pm2 kill"
echo "pm2 start ecosystem.config.js --update-env"