#!/bin/bash

# FIX SCRIPT voor Production Server
# Dit script lost het database connectie probleem op

echo "====================================="
echo "FIXING SERVER DATABASE CONNECTION"
echo "====================================="
echo ""
echo "Voer deze commands uit op de server:"
echo ""
echo "ssh root@209.38.40.156"
echo ""
echo "# 1. Check of .env file bestaat en niet leeg is:"
echo "cat /var/www/learnai/server/.env"
echo ""
echo "# 2. Als .env leeg is of niet bestaat, maak het aan:"
echo "cd /var/www/learnai/server"
echo ""
echo "# Maak .env file met de juiste settings:"
echo "cat > .env << 'EOF'"
echo "# Server Configuration"
echo "PORT=5000"
echo "NODE_ENV=production"
echo ""
echo "# Database Configuration"
echo "DB_HOST=localhost"
echo "DB_USER=root"
echo "DB_PASSWORD=BoomBoom10!Baby"
echo "DB_NAME=db"
echo "DB_PORT=3306"
echo ""
echo "# Security Keys"
echo "JWT_SECRET=your-production-jwt-secret-change-this-12345"
echo "JWT_EXPIRE=7d"
echo "SESSION_SECRET=your-production-session-secret-change-this-67890"
echo ""
echo "# Application URLs"
echo "FRONTEND_URL=http://209.38.40.156"
echo "BACKEND_URL=http://209.38.40.156:5000"
echo "EOF"
echo ""
echo "# 3. Check of het bestand correct is aangemaakt:"
echo "cat /var/www/learnai/server/.env"
echo ""
echo "# 4. Test database connectie met het wachtwoord:"
echo "mysql -h localhost -u root -pBoomBoom10!Baby -e 'SELECT 1'"
echo ""
echo "# 5. Restart PM2:"
echo "pm2 restart backend-server"
echo ""
echo "# 6. Check logs:"
echo "pm2 logs backend-server --lines 20"
echo ""
echo "# 7. Test health endpoint:"
echo "curl http://localhost:5000/api/health"
echo ""
echo "====================================="
echo "ALTERNATIEF: Kopieer vanaf je lokale machine"
echo "====================================="
echo ""
echo "Je kunt ook het .env bestand vanaf je lokale machine kopiëren:"
echo ""
echo "# Op je Windows machine:"
echo "scp C:/Users/Max/Documents/GIT/learnai/server/.env.production root@209.38.40.156:/var/www/learnai/server/.env"
echo ""
echo "# Dan op de server:"
echo "ssh root@209.38.40.156"
echo "cd /var/www/learnai/server"
echo "nano .env"
echo "# Verander DB_HOST naar localhost (niet 209.38.40.156)"
echo "# Save met Ctrl+X, Y, Enter"
echo ""
echo "pm2 restart backend-server"